### ISSUE TITLE
file request

### ISSUE THREAD

**Issue by spirit-icer** [thepowerfuldeez/age_gender_classifier#1]
Can you upload the file"labels.json"? Thanks a lot!

**Comment by spirit-icer** [comment]
> Can you upload the file"labels.json"? Thanks a lot!

**Comment by thepowerfuldeez** [comment]
Hi! For training I used https://talhassner.github.io/home/projects/Adience/Adience-data.html dataset. It has aligned folder and labels.json file inside. Thank you.
